// Generated from docs/formula-spec/tobe_formula_master.csv.
// Run: node tools/build_formula_catalog.js
window.FormulaMasterData = [
  {
    "id": "TBE-FLOW-001",
    "block": "Formula Trace",
    "name": "Calculation Trace",
    "formula": "input + source + variable + formula = result -> next block",
    "description": "Для каждой важной строки расчета нужно хранить проверяемую цепочку: что взяли, откуда, на что умножили, какой результат получили и куда он пошел дальше.",
    "source": "Все calculation blocks, variables, references.",
    "output": "Admin Cost Breakdown, audit snapshot.",
    "level": "Target Architecture",
    "usedIn": "Admin Cost Breakdown, audit snapshot."
  },
  {
    "id": "TBE-FLOW-002",
    "block": "Final Price Build Order",
    "name": "Build Sequence",
    "formula": "Inputs -> Route -> Items -> Vehicle/Crew -> Stages -> Fees -> Cost Base -> Margin/Fee/Discount -> Rounding -> Snapshot",
    "description": "Фиксирует порядок, в котором строится цена. Это главный контроль margin и воспроизводимости.",
    "source": "Pricing engine architecture.",
    "output": "Developer Formula Sprint implementation.",
    "level": "Target Architecture",
    "usedIn": "Developer Formula Sprint implementation."
  },
  {
    "id": "TBE-RTE-001",
    "block": "Route Type Pricing",
    "name": "Route Type",
    "formula": "routeType = consolidated / direct / specificDate / dedicated / corridor / remote / outOfZone",
    "description": "Заявка должна получить тип маршрута до расчета цены, потому что direct/specific-date/corridor/remote имеют другую экономику.",
    "source": "Pickup ZIP, delivery ZIP, service flags, ZIP dictionary.",
    "output": "Route, pickup, interstate, delivery pricing.",
    "level": "Target Architecture",
    "usedIn": "Route, pickup, interstate, delivery pricing."
  },
  {
    "id": "TBE-RTE-002",
    "block": "ZIP / Service Area",
    "name": "ZIP Dictionary",
    "formula": "ZIP -> serviceArea -> branch/warehouse -> zoneClass",
    "description": "ZIP dictionary должен быть отдельным справочником, а не частью формулы. Service area задает branch, warehouse point и zone class.",
    "source": "ZIP dictionary, service areas reference.",
    "output": "Distance, route support, zone fees.",
    "level": "Target Architecture",
    "usedIn": "Distance, route support, zone fees."
  },
  {
    "id": "TBE-RTE-003",
    "block": "Route / Distance",
    "name": "Distance Source",
    "formula": "IF direct/specificDate THEN exact/recalculated miles ELSE approved average/local distance",
    "description": "Для обычного consolidated route можно использовать approved average distance по зоне/филиалу; для direct/specific date нужно пересчитывать mileage.",
    "source": "Warehouse point, distance source, historical metrics.",
    "output": "Pickup/delivery mileage, direct fee, interstate cost.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery mileage, direct fee, interstate cost."
  },
  {
    "id": "TBE-RTE-004",
    "block": "Remote / Corridor",
    "name": "Remote Premium",
    "formula": "IF zoneClass = remote THEN cost x remoteCoefficient OR fixedRemoteFee",
    "description": "Удаленные зоны должны иметь отдельное правило доплаты, чтобы road cost не съедал margin.",
    "source": "ZIP/service area density analysis.",
    "output": "Route subtotal or service fee.",
    "level": "Target Architecture",
    "usedIn": "Route subtotal or service fee."
  },
  {
    "id": "TBE-ITM-001",
    "block": "Item Calculations",
    "name": "Physical Volume",
    "formula": "(Length x Width x Height / 1728) x Quantity",
    "description": "Считает физический объем item в cubic feet с учетом количества.",
    "source": "Item row / Quick Quote catalog transfer / item catalog defaults.",
    "output": "Effective volume, vehicle fit, total volume.",
    "level": "Target Architecture",
    "usedIn": "Effective volume, vehicle fit, total volume."
  },
  {
    "id": "TBE-ITM-002",
    "block": "Item Calculations",
    "name": "Effective Volume",
    "formula": "physicalVolume adjusted by stackability / fragile / crate / bulky / handling coefficients",
    "description": "Считает operational volume, который отражает не только физический размер, но и сложность перевозки.",
    "source": "Item row flags, catalog defaults, variables.",
    "output": "Vehicle fit, crew logic, labor model.",
    "level": "Target Architecture",
    "usedIn": "Vehicle fit, crew logic, labor model."
  },
  {
    "id": "TBE-ITM-003",
    "block": "Non-stack",
    "name": "Effective Height",
    "formula": "IF nonStack = TRUE THEN 96 in ELSE item height",
    "description": "Если предмет non-stackable, он занимает высоту 8 ft / 96 in для effective volume.",
    "source": "Item row non-stack checkbox, item height.",
    "output": "Effective volume.",
    "level": "Target Architecture",
    "usedIn": "Effective volume."
  },
  {
    "id": "TBE-ITM-004",
    "block": "Bulky / Moving",
    "name": "Bulky Premium",
    "formula": "IF totalVolume >= bulkyThreshold THEN bulkyPremium/reviewFlag",
    "description": "Большие moving-like заказы должны получать premium или обязательный review, чтобы быть выгодными.",
    "source": "Total volume, item count, route type.",
    "output": "Vehicle/crew/direct review/final price.",
    "level": "Target Architecture",
    "usedIn": "Vehicle/crew/direct review/final price."
  },
  {
    "id": "TBE-VEH-001",
    "block": "Vehicle",
    "name": "Vehicle Fit",
    "formula": "select smallest vehicle where capacityVolume >= effectiveVolume AND capacityWeight >= totalWeight",
    "description": "Vehicle выбирается по справочнику capacity, а не вручную и не hardcoded.",
    "source": "Effective volume, total weight, vehicle reference.",
    "output": "Interstate cost, local operations.",
    "level": "Target Architecture",
    "usedIn": "Interstate cost, local operations."
  },
  {
    "id": "TBE-CREW-001",
    "block": "Crew",
    "name": "Crew Split",
    "formula": "pickupCrew = f(pickup complexity); deliveryCrew = f(delivery complexity)",
    "description": "Pickup crew и delivery crew считаются отдельно, потому что pickup и delivery имеют разную трудоемкость.",
    "source": "Item totals, access conditions, labor reference.",
    "output": "Pickup labor, delivery labor.",
    "level": "Target Architecture",
    "usedIn": "Pickup labor, delivery labor."
  },
  {
    "id": "TBE-LAB-001",
    "block": "Labor",
    "name": "Pickup Time",
    "formula": "basePickupTime + itemCountRate + volumeRate + weightRate + accessImpact",
    "description": "Pickup time считается отдельно и может быть существенно выше delivery.",
    "source": "Item totals, pickup access fields, time metrics.",
    "output": "Pickup labor subtotal.",
    "level": "Target Architecture",
    "usedIn": "Pickup labor subtotal."
  },
  {
    "id": "TBE-LAB-002",
    "block": "Labor",
    "name": "Delivery Time",
    "formula": "baseDeliveryTime + itemCountRate + volumeRate + weightRate + accessImpact",
    "description": "Delivery time должен иметь собственные коэффициенты, не копировать pickup.",
    "source": "Item totals, delivery access fields, time metrics.",
    "output": "Delivery labor subtotal.",
    "level": "Target Architecture",
    "usedIn": "Delivery labor subtotal."
  },
  {
    "id": "TBE-DIR-001",
    "block": "Direct / Specific Date",
    "name": "Direct Fee",
    "formula": "IF direct/specificDate THEN fixedFee + exactMiles x mileageFee ELSE 0",
    "description": "Direct или specific-date service добавляет fixed fee и mileage fee; distance может пересчитываться отдельно.",
    "source": "Direct flag, specific date, distance source.",
    "output": "Pickup/direct/delivery subtotal.",
    "level": "Target Architecture",
    "usedIn": "Pickup/direct/delivery subtotal."
  },
  {
    "id": "TBE-INT-001",
    "block": "Interstate",
    "name": "Linehaul Cost",
    "formula": "interstateMiles x vehicle/route cost variables + fuel + driver + route premium",
    "description": "Interstate stage должен учитывать route type, distance, vehicle, fuel, driver and route premium.",
    "source": "Distance matrix, vehicle reference, fuel reference.",
    "output": "Interstate subtotal.",
    "level": "Target Architecture",
    "usedIn": "Interstate subtotal."
  },
  {
    "id": "TBE-FEE-001",
    "block": "Custom Crate",
    "name": "Crate Cost",
    "formula": "surfaceArea x materialPrice x wasteCoefficient + laborHours x laborRate + margin",
    "description": "Crate считается от площади внешних размеров, материала, waste/cuts, labor и margin.",
    "source": "Item dimensions, material reference, labor reference.",
    "output": "Packaging/crate subtotal.",
    "level": "Target Architecture",
    "usedIn": "Packaging/crate subtotal."
  },
  {
    "id": "TBE-FEE-002",
    "block": "Protection",
    "name": "RV / FVP / DV",
    "formula": "RV = included; FVP = declaredValue x rate + fixedFee once per order; DV = future/confirmation",
    "description": "Protection pricing должен использовать declared value, а не item reference price. FVP fixed fee применяется один раз на order.",
    "source": "Protection plan field, declared value input, protection reference.",
    "output": "Protection cost, customer wording.",
    "level": "Target Architecture",
    "usedIn": "Protection cost, customer wording."
  },
  {
    "id": "TBE-FEE-003",
    "block": "Storage",
    "name": "Storage Cost",
    "formula": "billableVolume x storageDays x storageRate",
    "description": "Storage остается отдельным cost component и должен сохранять совместимость со старыми estimate snapshots.",
    "source": "Item storage fields, volume, storage variables.",
    "output": "Service fees subtotal, snapshot.",
    "level": "Target Architecture",
    "usedIn": "Service fees subtotal, snapshot."
  },
  {
    "id": "TBE-ACC-001",
    "block": "Access",
    "name": "Floor / Elevator / COI",
    "formula": "approved access rule by stage; avoid double-counting with labor time",
    "description": "Access условия могут быть fee или time impact, но не должны дублироваться в labor.",
    "source": "Floor, elevator, COI, stairs, long carry.",
    "output": "Pickup/delivery/service subtotal.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery/service subtotal."
  },
  {
    "id": "TBE-MGN-001",
    "block": "Margin",
    "name": "Margin Application",
    "formula": "marginAmount = approvedCostBase x marginRate",
    "description": "Margin применяется к утвержденной cost base в утвержденном порядке.",
    "source": "Stage subtotals, service fees, margin variable.",
    "output": "Raw customer price.",
    "level": "Target Architecture",
    "usedIn": "Raw customer price."
  },
  {
    "id": "TBE-MGN-002",
    "block": "Discount",
    "name": "Discount Guardrail",
    "formula": "discount applies after approved margin/fee step and checks margin floor",
    "description": "Discount должен быть auditable и не должен ломать минимальную прибыльность.",
    "source": "Discount input, approval reason, margin floor.",
    "output": "Final raw price, audit.",
    "level": "Target Architecture",
    "usedIn": "Final raw price, audit."
  },
  {
    "id": "TBE-FINAL-001",
    "block": "Final Total",
    "name": "Rounding",
    "formula": "finalCustomerPrice = CEILING(rawCustomerPrice, roundingIncrement)",
    "description": "Клиент видит округленную цену без лишних cents; raw price и rounding delta сохраняются внутри.",
    "source": "Raw customer price, rounding variable.",
    "output": "Estimate Document, snapshot.",
    "level": "Target Architecture",
    "usedIn": "Estimate Document, snapshot."
  },
  {
    "id": "TBE-SNAP-001",
    "block": "Snapshot",
    "name": "Immutable Estimate",
    "formula": "snapshot = quote + result + trace + formulaVersion + variablesSnapshot + referencesVersion",
    "description": "Estimate должен быть frozen snapshot. Draft может пересчитываться, estimate не должен silently recalc.",
    "source": "Pricing result, quote payload, variables, references.",
    "output": "My Estimates, Cost Breakdown, audit.",
    "level": "Target Architecture",
    "usedIn": "My Estimates, Cost Breakdown, audit."
  },
  {
    "id": "TBE-GOV-001",
    "block": "Variable Governance",
    "name": "Editable Variable Rule",
    "formula": "editableVariable = hasOwner AND hasApprovalRule AND hasBenchmarkPreview",
    "description": "Переменную можно редактировать в admin только если у нее есть владелец, правило approval и preview влияния на benchmark cases.",
    "source": "Variable governance reference.",
    "output": "Admin settings, release control.",
    "level": "Target Architecture",
    "usedIn": "Admin settings, release control."
  },
  {
    "id": "TBE-LAB-003",
    "block": "Labor",
    "name": "Total Pickup Labor Hours",
    "formula": "pickupLaborHours = pickupMinutes / 60 x pickupCrew",
    "description": "Переводит расчетное pickup time в человеко-часы: если 2 человека работают 45 минут, это 1.5 человеко-часа.",
    "source": "Pickup time model, pickup crew.",
    "output": "Pickup payroll cost, stage labor cost, productivity metrics.",
    "level": "Target Architecture",
    "usedIn": "Pickup payroll cost, stage labor cost, productivity metrics."
  },
  {
    "id": "TBE-LAB-004",
    "block": "Labor",
    "name": "Total Delivery Labor Hours",
    "formula": "deliveryLaborHours = deliveryMinutes / 60 x deliveryCrew",
    "description": "Переводит delivery time в человеко-часы отдельно от pickup, чтобы видеть реальную трудоемкость delivery stage.",
    "source": "Delivery time model, delivery crew.",
    "output": "Delivery payroll cost, stage labor cost, productivity metrics.",
    "level": "Target Architecture",
    "usedIn": "Delivery payroll cost, stage labor cost, productivity metrics."
  },
  {
    "id": "TBE-LAB-005",
    "block": "Labor",
    "name": "Helper Labor Hours",
    "formula": "helperHours = helperCount x max(helperMinutes, minHelperMinutes) / 60",
    "description": "Считает человеко-часы дополнительных helpers с учетом минимального оплачиваемого времени.",
    "source": "Heavy/bulky/access flags, helper count, min helper time.",
    "output": "Helper payroll, access/labor surcharge.",
    "level": "Target Architecture",
    "usedIn": "Helper payroll, access/labor surcharge."
  },
  {
    "id": "TBE-LAB-006",
    "block": "Labor",
    "name": "Billable vs Paid Labor Hours",
    "formula": "laborVariance = billableLaborHours - paidLaborHours",
    "description": "Разделяет customer-billable labor и payroll-paid labor, чтобы видеть маржу на labor и не путать цену с выплатами.",
    "source": "Billable minutes, actual/paid minutes, crew records.",
    "output": "Labor margin, payroll audit, productivity analysis.",
    "level": "Target Architecture",
    "usedIn": "Labor margin, payroll audit, productivity analysis."
  },
  {
    "id": "TBE-LAB-007",
    "block": "Labor",
    "name": "Labor Productivity Rate",
    "formula": "productivity = totalEffectiveVolume / totalLaborHours",
    "description": "Показывает, сколько cu ft обрабатывается за человеко-час. Нужно для калибровки pickup/delivery time model.",
    "source": "Effective volume, labor hours.",
    "output": "Operations metrics, coefficient calibration.",
    "level": "Target Architecture",
    "usedIn": "Operations metrics, coefficient calibration."
  },
  {
    "id": "TBE-PAY-001",
    "block": "Payroll",
    "name": "Crew Base Pay",
    "formula": "crewBasePay = paidLaborHours x hourlyWage",
    "description": "Считает базовую зарплату crew по фактически оплачиваемым человеко-часам и ставке.",
    "source": "Paid labor hours, wage reference.",
    "output": "Payroll cost, fully loaded cost.",
    "level": "Target Architecture",
    "usedIn": "Payroll cost, fully loaded cost."
  },
  {
    "id": "TBE-PAY-002",
    "block": "Payroll",
    "name": "Crew Overtime Pay",
    "formula": "overtimePay = overtimeHours x hourlyWage x overtimeMultiplier",
    "description": "Считает overtime отдельно, чтобы большие/сложные заказы не занижали payroll cost.",
    "source": "Paid hours, overtime threshold, wage reference.",
    "output": "Payroll cost, profitability guardrail.",
    "level": "Target Architecture",
    "usedIn": "Payroll cost, profitability guardrail."
  },
  {
    "id": "TBE-PAY-003",
    "block": "Payroll",
    "name": "Payroll Burden",
    "formula": "payrollBurden = crewGrossPay x payrollBurdenRate",
    "description": "Добавляет payroll taxes/insurance/benefits burden к зарплате, чтобы margin считался по fully loaded labor cost.",
    "source": "Crew gross pay, payroll burden rate.",
    "output": "Fully loaded labor cost.",
    "level": "Target Architecture",
    "usedIn": "Fully loaded labor cost."
  },
  {
    "id": "TBE-PAY-004",
    "block": "Payroll",
    "name": "Total Crew Cost",
    "formula": "totalCrewCost = crewBasePay + overtimePay + payrollBurden + helperPay",
    "description": "Собирает полную cost of labor по заказу или stage.",
    "source": "Crew pay components, helper pay.",
    "output": "Operational cost base, contribution margin.",
    "level": "Target Architecture",
    "usedIn": "Operational cost base, contribution margin."
  },
  {
    "id": "TBE-PAY-005",
    "block": "Payroll",
    "name": "Stage Labor Cost Allocation",
    "formula": "stageLaborCost = laborHoursByStage x fullyLoadedHourlyRate",
    "description": "Распределяет fully loaded labor cost по pickup/interstate/delivery, чтобы маржинальность была видна по stage.",
    "source": "Labor hours by stage, fully loaded hourly rate.",
    "output": "Stage subtotal, stage margin analysis.",
    "level": "Target Architecture",
    "usedIn": "Stage subtotal, stage margin analysis."
  },
  {
    "id": "TBE-BRK-001",
    "block": "Broker Payout",
    "name": "Broker Commission Base",
    "formula": "brokerCommissionBase = approvedRevenueBase - excludedFees",
    "description": "Определяет базу, от которой считается выплата broker. Некоторые fees могут исключаться.",
    "source": "Final price, service fees, excluded fee list.",
    "output": "Broker commission.",
    "level": "Target Architecture",
    "usedIn": "Broker commission."
  },
  {
    "id": "TBE-BRK-002",
    "block": "Broker Payout",
    "name": "Broker Commission",
    "formula": "brokerCommission = brokerCommissionBase x brokerCommissionRate",
    "description": "Считает выплату broker как процент от утвержденной базы.",
    "source": "Commission base, broker commission rate.",
    "output": "Broker payout, net margin.",
    "level": "Target Architecture",
    "usedIn": "Broker payout, net margin."
  },
  {
    "id": "TBE-BRK-003",
    "block": "Broker Payout",
    "name": "Broker Minimum / Cap",
    "formula": "brokerPayout = min(max(calculatedCommission, minPayout), maxPayout)",
    "description": "Ограничивает broker payout минимумом/максимумом, чтобы выплаты были предсказуемы.",
    "source": "Calculated commission, payout min/max.",
    "output": "Broker payout, final profitability.",
    "level": "Target Architecture",
    "usedIn": "Broker payout, final profitability."
  },
  {
    "id": "TBE-BRK-004",
    "block": "Broker Payout",
    "name": "Broker Payout Eligibility",
    "formula": "eligiblePayout = IF(orderStatus/paymentStatus qualifies, brokerPayout, 0)",
    "description": "Проверяет, когда broker payout должен начисляться: после estimate, invoice, payment, pickup или delivery.",
    "source": "Order status, payment status, payout policy.",
    "output": "Broker payout accrual.",
    "level": "Target Architecture",
    "usedIn": "Broker payout accrual."
  },
  {
    "id": "TBE-DSP-001",
    "block": "Dispatcher Payout",
    "name": "Dispatcher Payout Base",
    "formula": "dispatcherPayoutBase = ordersHandled x ratePerOrder OR revenueBase x dispatcherRate",
    "description": "Определяет базу для выплаты dispatcher: per order, процент от revenue или гибрид.",
    "source": "Orders handled, revenue base, dispatcher plan.",
    "output": "Dispatcher payout.",
    "level": "Target Architecture",
    "usedIn": "Dispatcher payout."
  },
  {
    "id": "TBE-DSP-002",
    "block": "Dispatcher Payout",
    "name": "Dispatcher Payout",
    "formula": "dispatcherPayout = dispatcherPayoutBase + bonus - penalty",
    "description": "Считает итоговую выплату dispatcher с бонусами/штрафами, если они применяются.",
    "source": "Dispatcher base, bonus rules, penalty rules.",
    "output": "Payroll/admin payout, profitability.",
    "level": "Target Architecture",
    "usedIn": "Payroll/admin payout, profitability."
  },
  {
    "id": "TBE-DSP-003",
    "block": "Dispatcher Payout",
    "name": "Dispatcher Stage Allocation",
    "formula": "dispatcherStageCost = dispatcherPayout x stageShare",
    "description": "Распределяет dispatcher payout по pickup/interstate/delivery, чтобы stage margin был честным.",
    "source": "Dispatcher payout, stage share rule.",
    "output": "Stage cost and margin.",
    "level": "Target Architecture",
    "usedIn": "Stage cost and margin."
  },
  {
    "id": "TBE-COST-001",
    "block": "Cost Base",
    "name": "Direct Operational Cost",
    "formula": "directCost = pickupCost + interstateCost + deliveryCost + serviceFees",
    "description": "Собирает прямую себестоимость заказа до overhead, payouts, margin и discounts.",
    "source": "Stage subtotals, service fees.",
    "output": "Fully loaded cost, margin calculation.",
    "level": "Target Architecture",
    "usedIn": "Fully loaded cost, margin calculation."
  },
  {
    "id": "TBE-COST-002",
    "block": "Cost Base",
    "name": "Fully Loaded Cost",
    "formula": "fullyLoadedCost = directCost + payrollBurden + brokerPayout + dispatcherPayout + overheadAllocation",
    "description": "Считает полную себестоимость заказа для правильной маржинальности.",
    "source": "Direct cost, payroll, payouts, overhead.",
    "output": "Gross/contribution margin, price floor.",
    "level": "Target Architecture",
    "usedIn": "Gross/contribution margin, price floor."
  },
  {
    "id": "TBE-COST-003",
    "block": "Cost Allocation",
    "name": "Item Cost Allocation",
    "formula": "itemCostShare = itemEffectiveVolume / totalEffectiveVolume x allocatableCost",
    "description": "Распределяет cost по item для audit/ref price, не как declared value.",
    "source": "Item effective volume, total effective volume, allocatable cost.",
    "output": "Item-level audit, internal allocation.",
    "level": "Target Architecture",
    "usedIn": "Item-level audit, internal allocation."
  },
  {
    "id": "TBE-COST-004",
    "block": "Cost Allocation",
    "name": "Stage Cost Allocation",
    "formula": "stageCostShare = stageCost / totalCost",
    "description": "Показывает, какая доля себестоимости пришлась на pickup/interstate/delivery.",
    "source": "Stage costs, total cost.",
    "output": "Stage margin dashboard, CEO audit.",
    "level": "Target Architecture",
    "usedIn": "Stage margin dashboard, CEO audit."
  },
  {
    "id": "TBE-MGN-003",
    "block": "Margin",
    "name": "Gross Margin Dollars",
    "formula": "grossMargin = customerRevenue - directOperationalCost",
    "description": "Считает gross margin в долларах до fully loaded payouts/overhead.",
    "source": "Customer revenue, direct cost.",
    "output": "CEO profitability view.",
    "level": "Target Architecture",
    "usedIn": "CEO profitability view."
  },
  {
    "id": "TBE-MGN-004",
    "block": "Margin",
    "name": "Gross Margin Percent",
    "formula": "grossMarginPct = grossMargin / customerRevenue",
    "description": "Показывает gross margin в процентах от customer revenue.",
    "source": "Gross margin, customer revenue.",
    "output": "Margin guardrails, reporting.",
    "level": "Target Architecture",
    "usedIn": "Margin guardrails, reporting."
  },
  {
    "id": "TBE-MGN-005",
    "block": "Margin",
    "name": "Contribution Margin Dollars",
    "formula": "contributionMargin = customerRevenue - fullyLoadedCost",
    "description": "Считает contribution margin после payroll burden, broker/dispatcher payouts и approved overhead.",
    "source": "Customer revenue, fully loaded cost.",
    "output": "Profitability guardrail.",
    "level": "Target Architecture",
    "usedIn": "Profitability guardrail."
  },
  {
    "id": "TBE-MGN-006",
    "block": "Margin",
    "name": "Contribution Margin Percent",
    "formula": "contributionMarginPct = contributionMargin / customerRevenue",
    "description": "Показывает реальную маржинальность заказа после всех ключевых выплат и cost components.",
    "source": "Contribution margin, customer revenue.",
    "output": "CEO/CFO margin dashboard.",
    "level": "Target Architecture",
    "usedIn": "CEO/CFO margin dashboard."
  },
  {
    "id": "TBE-MGN-007",
    "block": "Margin",
    "name": "Minimum Margin Guardrail",
    "formula": "isMarginOk = contributionMarginPct >= minContributionMarginPct",
    "description": "Блокирует или помечает quote, если цена ниже минимальной маржинальности.",
    "source": "Contribution margin pct, minimum margin pct.",
    "output": "Warning/blocker, discount approval.",
    "level": "Target Architecture",
    "usedIn": "Warning/blocker, discount approval."
  },
  {
    "id": "TBE-MGN-008",
    "block": "Margin",
    "name": "Price Floor",
    "formula": "priceFloor = fullyLoadedCost / (1 - minContributionMarginPct)",
    "description": "Считает минимальную customer price, ниже которой заказ не должен продаваться.",
    "source": "Fully loaded cost, minimum margin pct.",
    "output": "Discount guardrail, final quote check.",
    "level": "Target Architecture",
    "usedIn": "Discount guardrail, final quote check."
  },
  {
    "id": "TBE-MGN-009",
    "block": "Discount",
    "name": "Maximum Allowed Discount",
    "formula": "maxDiscount = rawCustomerPrice - priceFloor",
    "description": "Считает максимальную скидку, которую можно дать без нарушения margin floor.",
    "source": "Raw customer price, price floor.",
    "output": "Discount approval, warning/blocker.",
    "level": "Target Architecture",
    "usedIn": "Discount approval, warning/blocker."
  },
  {
    "id": "TBE-MGN-010",
    "block": "Discount",
    "name": "Post-Discount Margin Check",
    "formula": "postDiscountMarginPct = (discountedPrice - fullyLoadedCost) / discountedPrice",
    "description": "Пересчитывает margin после скидки, чтобы discount не разрушал прибыльность.",
    "source": "Discounted price, fully loaded cost.",
    "output": "Final approval, audit.",
    "level": "Target Architecture",
    "usedIn": "Final approval, audit."
  },
  {
    "id": "TBE-CAP-001",
    "block": "Capacity",
    "name": "Vehicle Space Utilization",
    "formula": "vehicleUtilization = totalEffectiveVolume / selectedVehicleCapacity",
    "description": "Показывает, насколько выбранная машина заполнена по operational volume.",
    "source": "Effective volume, selected vehicle capacity.",
    "output": "Vehicle fit, capacity warning, pricing premium.",
    "level": "Target Architecture",
    "usedIn": "Vehicle fit, capacity warning, pricing premium."
  },
  {
    "id": "TBE-CAP-002",
    "block": "Capacity",
    "name": "Payload Utilization",
    "formula": "payloadUtilization = totalWeight / selectedVehiclePayload",
    "description": "Показывает загрузку vehicle по весу, отдельно от объема.",
    "source": "Total weight, selected vehicle payload.",
    "output": "Vehicle fit, safety/ops warning.",
    "level": "Target Architecture",
    "usedIn": "Vehicle fit, safety/ops warning."
  },
  {
    "id": "TBE-CAP-003",
    "block": "Capacity",
    "name": "Route Capacity Opportunity Cost",
    "formula": "capacityOpportunityCost = reservedCapacity x routeCapacityRate",
    "description": "Оценивает стоимость занятой capacity на route, особенно для bulky/moving orders.",
    "source": "Reserved capacity, route capacity rate.",
    "output": "Bulky premium, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Bulky premium, margin guardrail."
  },
  {
    "id": "TBE-CAP-004",
    "block": "Capacity",
    "name": "Bulky Capacity Premium",
    "formula": "bulkyCapacityPremium = capacityOpportunityCost x bulkyPremiumMultiplier",
    "description": "Добавляет premium, когда заказ занимает слишком много capacity и мешает consolidated economics.",
    "source": "Capacity opportunity cost, bulky multiplier.",
    "output": "Service fee or route premium.",
    "level": "Target Architecture",
    "usedIn": "Service fee or route premium."
  },
  {
    "id": "TBE-REV-001",
    "block": "Revenue",
    "name": "Customer Revenue",
    "formula": "customerRevenue = finalCustomerPrice - passThroughExcludedAmounts",
    "description": "Определяет revenue base для margin, commissions and reporting.",
    "source": "Final price, pass-through fees.",
    "output": "Margin, broker payout, reporting.",
    "level": "Target Architecture",
    "usedIn": "Margin, broker payout, reporting."
  },
  {
    "id": "TBE-REV-002",
    "block": "Revenue",
    "name": "Stage Revenue Allocation",
    "formula": "stageRevenue = customerRevenue x stageCost / totalCost",
    "description": "Распределяет revenue по pickup/interstate/delivery пропорционально cost, чтобы видеть stage margin.",
    "source": "Customer revenue, stage cost shares.",
    "output": "Stage margin dashboard.",
    "level": "Target Architecture",
    "usedIn": "Stage margin dashboard."
  },
  {
    "id": "TBE-ADJ-001",
    "block": "Adjustments",
    "name": "Approved Manual Override Impact",
    "formula": "overrideImpact = approvedOverrideAmount; finalImpact stored with reason and owner",
    "description": "Любой manual override должен иметь reason, owner и audit trail, чтобы не скрывать margin leakage.",
    "source": "Approved override, reason, owner.",
    "output": "Final price, margin audit, change log.",
    "level": "Target Architecture",
    "usedIn": "Final price, margin audit, change log."
  },
  {
    "id": "TBE-LOC-001",
    "block": "Location / Address Type",
    "name": "Address Type Normalization",
    "formula": "normalizedAddressType = MAP(rawAddressType, LocationTypeReference)",
    "description": "Тип точки из UI должен нормализоваться в единый справочник. Это нужно, чтобы House, Apartments, Business, Warehouse и Auction одинаково использовались в pickup и delivery расчетах.",
    "source": "Pickup/delivery addressType from Quote Draft access section; Location / Address Types reference.",
    "output": "Pickup/delivery time model, access effort, crew planning.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery time model, access effort, crew planning."
  },
  {
    "id": "TBE-LOC-002",
    "block": "Location / Address Type",
    "name": "Location Type Time Impact",
    "formula": "locationTimeMinutes = baseStageMinutes x locationTypeTimeMultiplier + locationTypeFixedMinutes",
    "description": "Тип точки должен увеличивать или уменьшать расчетное время stage. Например, apartment может добавить время доступа, warehouse может снизить handling time, auction может добавить waiting/release time.",
    "source": "Normalized address type; Location / Address Types reference; historical time metrics.",
    "output": "Pickup minutes, delivery minutes, labor hours, fully loaded labor cost.",
    "level": "Target Architecture",
    "usedIn": "Pickup minutes, delivery minutes, labor hours, fully loaded labor cost."
  },
  {
    "id": "TBE-LOC-003",
    "block": "Location / Address Type",
    "name": "Location Type Crew Impact",
    "formula": "recommendedCrew = baseCrew + locationTypeCrewImpact + accessCrewImpact",
    "description": "Тип точки должен влиять на рекомендуемый crew, если локация требует больше людей или создает ограничения доступа. Это planning input, не скрытая ручная наценка.",
    "source": "Location / Address Types reference; Access Conditions; crew rules.",
    "output": "Vehicle/crew split, labor cost, capacity planning.",
    "level": "Target Architecture",
    "usedIn": "Vehicle/crew split, labor cost, capacity planning."
  },
  {
    "id": "TBE-LOC-004",
    "block": "Location / Address Type",
    "name": "Parking / Loading Complexity",
    "formula": "accessEffortMinutes = parkingLoadingComplexityMinutes + loadingDockPenalty + waitTimeAllowance",
    "description": "Для точки нужно учитывать не только этаж/лифт, но и парковку, loading dock, building access и ожидание. Эти минуты идут в stage time и стоимость труда.",
    "source": "Location / Address Types reference; Access Conditions; historical time metrics.",
    "output": "Pickup/delivery labor minutes and access risk.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery labor minutes and access risk."
  },
  {
    "id": "TBE-LOC-005",
    "block": "Location / Address Type",
    "name": "Warehouse Efficiency Adjustment",
    "formula": "adjustedHandlingMinutes = handlingMinutes x warehouseEfficiencyFactor",
    "description": "Warehouse/business точка может быть быстрее, если есть dock/loading process. Коэффициент должен быть в справочнике, чтобы не hardcode в формуле.",
    "source": "Location / Address Types reference; loading dock/default access fields.",
    "output": "Pickup/delivery handling time, labor cost.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery handling time, labor cost."
  },
  {
    "id": "TBE-LOC-006",
    "block": "Location / Address Type",
    "name": "Auction Handling Adjustment",
    "formula": "auctionHandlingCost = auctionHandlingMinutes / 60 x fullyLoadedHourlyRate x crewSize",
    "description": "Auction требует отдельного handling allowance: ожидание, release, документы, ограниченные окна. Без этого калькулятор может недооценивать labor cost.",
    "source": "Location / Address Types reference; payroll/wage rates; historical time metrics.",
    "output": "Pickup/delivery labor cost, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery labor cost, margin guardrail."
  },
  {
    "id": "TBE-LOC-007",
    "block": "Location / Address Type",
    "name": "Location Effort Score",
    "formula": "locationEffortScore = accessComplexityMultiplier + parkingComplexityScore + waitRiskScore + locationTypeCrewImpact",
    "description": "Сводный effort score показывает операционную сложность точки. Он не заменяет деньги напрямую, а помогает объяснить, почему выросли time, crew или risk reserve.",
    "source": "Location / Address Types reference; Access Conditions; historical time metrics.",
    "output": "Time model, crew planning, margin guardrail, audit trace.",
    "level": "Target Architecture",
    "usedIn": "Time model, crew planning, margin guardrail, audit trace."
  },
  {
    "id": "TBE-LOC-008",
    "block": "Location / Address Type",
    "name": "Location Risk Reserve",
    "formula": "locationRiskReserve = locationLaborCost x locationRiskReservePct when confidence is low or effortScore exceeds threshold",
    "description": "Если тип точки исторически дает высокий риск ожидания/переработки, модель должна показывать отдельный reserve, чтобы CEO видел источник защиты маржи.",
    "source": "Location effort score; time confidence score; margin variables.",
    "output": "Internal cost base or management fee decision, depending on approval.",
    "level": "Target Architecture",
    "usedIn": "Internal cost base or management fee decision, depending on approval."
  },
  {
    "id": "TBE-HND-001",
    "block": "Item Handling / Crew Feasibility",
    "name": "Max Single Item Weight",
    "formula": "maxSingleItemWeight = MAX(unitItemWeight)",
    "description": "Для решения one-person vs two-person смотрим вес самой тяжелой отдельной единицы, а не item weight x quantity. Quantity считается отдельно через totalPieces и totalWeight.",
    "source": "Quote Draft item rows / Quick Quote catalog transfer; unit item weight per piece.",
    "output": "One-person eligibility, min crew by item, pickup/delivery labor model.",
    "level": "Target Architecture",
    "usedIn": "One-person eligibility, min crew by item, pickup/delivery labor model."
  },
  {
    "id": "TBE-HND-002",
    "block": "Item Handling / Crew Feasibility",
    "name": "Heaviest Item Weight Class",
    "formula": "weightClass = LOOKUP(maxSingleItemWeight, Item Handling Rules weight bands)",
    "description": "Самый тяжелый предмет переводится в weight class: light, standard, heavy, two-person required. Это предотвращает underpricing маленьких по объему, но тяжелых предметов.",
    "source": "Max single item weight; Item Handling / Crew Feasibility Rules reference.",
    "output": "Crew requirement, helper logic, handling score.",
    "level": "Target Architecture",
    "usedIn": "Crew requirement, helper logic, handling score."
  },
  {
    "id": "TBE-HND-003",
    "block": "Item Handling / Crew Feasibility",
    "name": "One-Person Eligibility",
    "formula": "onePersonEligible = maxSingleItemWeight <= onePersonMaxItemWeightLb AND noHardAccessConstraint AND noOversizedAwkwardItem",
    "description": "Заказ может быть кандидатом на delivery в одного человека, если самый тяжелый предмет не превышает approved threshold и нет ограничений access/oversized/awkward.",
    "source": "Max item weight, access constraints, item flags, Location / Address Types reference.",
    "output": "Delivery crew split, pickup crew split, labor cost.",
    "level": "Target Architecture",
    "usedIn": "Delivery crew split, pickup crew split, labor cost."
  },
  {
    "id": "TBE-HND-004",
    "block": "Item Handling / Crew Feasibility",
    "name": "Minimum Crew By Item",
    "formula": "minCrewByItem = MAX(ItemHandlingRules[item].minCrew)",
    "description": "Каждый item может требовать minimum crew. Итоговый crew не может быть ниже максимального требования по любому предмету в заказе.",
    "source": "Item catalog, item handling rules, custom item overrides.",
    "output": "Recommended crew, labor hours, payroll cost.",
    "level": "Target Architecture",
    "usedIn": "Recommended crew, labor hours, payroll cost."
  },
  {
    "id": "TBE-HND-005",
    "block": "Item Handling / Crew Feasibility",
    "name": "Large Volume Light Item Exception",
    "formula": "largeLightEligible = totalEffectiveVolume > largeLightItemVolumeThresholdCuFt AND maxSingleItemWeight <= onePersonMaxItemWeightLb AND itemHandlingScore < threshold",
    "description": "Большой общий объем сам по себе не должен автоматически означать 2+ crew, если заказ состоит из легких предметов вроде стульев/кресел и каждый предмет доступен для одного человека.",
    "source": "Total effective volume, max single item weight, item handling score, item catalog.",
    "output": "Crew split, labor time model, CEO approval trace.",
    "level": "Target Architecture",
    "usedIn": "Crew split, labor time model, CEO approval trace."
  },
  {
    "id": "TBE-HND-006",
    "block": "Item Handling / Crew Feasibility",
    "name": "Item Handling Score",
    "formula": "itemHandlingScore = weightScore + sizeScore + awkwardnessScore + fragilityScore + packagingScore + accessInteractionScore",
    "description": "Score объясняет, почему предмет требует больше времени/людей: вес, габарит, неудобная форма, хрупкость, упаковка и взаимодействие с access условиями.",
    "source": "Item rows, item catalog flags, packaging, protection, access/location references.",
    "output": "Minimum handling minutes, crew requirement, risk reserve.",
    "level": "Target Architecture",
    "usedIn": "Minimum handling minutes, crew requirement, risk reserve."
  },
  {
    "id": "TBE-HND-007",
    "block": "Item Handling / Crew Feasibility",
    "name": "Crew Requirement From Items",
    "formula": "crewFromItems = IF(onePersonEligible, 1, MAX(minCrewByItem, crewByHandlingScore))",
    "description": "Crew от items считается отдельно от route/location/access. Это защищает от ситуации, когда volume маленький, но предмет требует 2 человек.",
    "source": "One-person eligibility, item min crew, handling score.",
    "output": "Final pickup crew, final delivery crew, labor hours.",
    "level": "Target Architecture",
    "usedIn": "Final pickup crew, final delivery crew, labor hours."
  },
  {
    "id": "TBE-HND-008",
    "block": "Item Handling / Crew Feasibility",
    "name": "Final Stage Crew Requirement",
    "formula": "stageCrew = MAX(baseCrew, crewFromItems, crewFromAccess, crewFromLocation, manualCrewOverride)",
    "description": "Итоговый crew для pickup/delivery берется как максимум из item, access, location и manual override. Так ни один риск не затирается другим блоком.",
    "source": "Item handling rules, access conditions, location type, broker/manual override.",
    "output": "Pickup labor hours, delivery labor hours, payroll cost, final price.",
    "level": "Target Architecture",
    "usedIn": "Pickup labor hours, delivery labor hours, payroll cost, final price."
  },
  {
    "id": "TBE-HND-009",
    "block": "Item Handling / Crew Feasibility",
    "name": "Item Minimum Handling Time Floor",
    "formula": "stageItemTimeFloor = SUM(itemMinimumHandlingMinutes x quantity x handlingComplexityMultiplier)",
    "description": "Даже если volume небольшой, каждый предмет имеет minimum handling time. Это защищает расчет от занижения labor для тяжелых или неудобных единичных предметов.",
    "source": "Item Handling Rules, item quantity, handling class.",
    "output": "Pickup/delivery time floor, labor cost.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery time floor, labor cost."
  },
  {
    "id": "TBE-HND-010",
    "block": "Item Handling / Crew Feasibility",
    "name": "Stage Time Guardrail",
    "formula": "stageMinutes = MAX(orderLevelTimeModelMinutes, stageItemTimeFloor)",
    "description": "Финальное время stage не может быть ниже суммы item-level minimum handling time. Order-level volume model и item-level floor работают вместе.",
    "source": "Order time model, item minimum handling floor.",
    "output": "Pickup/delivery labor cost, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery labor cost, margin guardrail."
  },
  {
    "id": "TBE-HND-011",
    "block": "Item Handling / Crew Feasibility",
    "name": "Unit Item Weight",
    "formula": "unitItemWeight = item.weight",
    "description": "Фиксирует вес одной физической единицы. Это защищает от ошибки, когда 10 легких предметов по 20 lb превращаются в один фиктивный heavy item 200 lb.",
    "source": "Quote Draft item row / catalog default / broker override.",
    "output": "Max single item weight, heavy piece count, one-person eligibility.",
    "level": "Target Architecture",
    "usedIn": "Max single item weight, heavy piece count, one-person eligibility."
  },
  {
    "id": "TBE-HND-012",
    "block": "Item Handling / Crew Feasibility",
    "name": "Total Pieces",
    "formula": "totalPieces = SUM(item.quantity)",
    "description": "Считает количество мест/единиц в заказе. Piece count влияет на время обработки, но не должен сам создавать heavy item.",
    "source": "Quote Draft item quantities / Quick Quote transfer.",
    "output": "Piece handling minutes, trip/load complexity, UAT trace.",
    "level": "Target Architecture",
    "usedIn": "Piece handling minutes, trip/load complexity, UAT trace."
  },
  {
    "id": "TBE-HND-013",
    "block": "Item Handling / Crew Feasibility",
    "name": "Heavy Piece Count",
    "formula": "heavyPieceCount = SUM(IF(unitItemWeight >= heavyPieceWeightThresholdLb, quantity, 0))",
    "description": "Считает, сколько физических единиц являются тяжелыми. Один тяжелый предмет задает crew floor, а несколько тяжелых предметов увеличивают helper active time.",
    "source": "Unit item weight, quantity, Item Handling Rules.",
    "output": "Crew requirement, helper active minutes, stage time floor.",
    "level": "Target Architecture",
    "usedIn": "Crew requirement, helper active minutes, stage time floor."
  },
  {
    "id": "TBE-HND-014",
    "block": "Item Handling / Crew Feasibility",
    "name": "Piece Handling Time",
    "formula": "pieceHandlingMinutes = SUM(quantity x minutesPerPieceByHandlingClass)",
    "description": "Каждое место требует минимального времени обработки. Это закрывает кейс 35 легких мест, где общий вес небольшой, но физически много операций.",
    "source": "Item Handling Rules, handling class, item quantity.",
    "output": "Stage item time floor, pickup/delivery labor minutes.",
    "level": "Target Architecture",
    "usedIn": "Stage item time floor, pickup/delivery labor minutes."
  },
  {
    "id": "TBE-HND-015",
    "block": "Item Handling / Crew Feasibility",
    "name": "Helper Active Minutes",
    "formula": "helperActiveMinutes = SUM(heavyPieceHandlingMinutes + accessHeavyImpactMinutes)",
    "description": "Считает время, когда второй человек действительно нужен для тяжелых/сложных предметов. Это позволяет не умножать весь stage на 2, если helper нужен только на часть работ.",
    "source": "Heavy piece count, item handling minutes, access constraints.",
    "output": "Partial helper labor, payroll cost, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Partial helper labor, payroll cost, margin guardrail."
  },
  {
    "id": "TBE-HND-016",
    "block": "Item Handling / Crew Feasibility",
    "name": "Labor Hours With Partial Helper",
    "formula": "laborHours = soloMinutes / 60 + helperActiveMinutes / 60",
    "description": "Разделяет базовое время одного исполнителя и активное время helper. Используется, если бизнес не хочет считать 2 человека на весь stage.",
    "source": "Stage minutes, helper active minutes, helper billing policy.",
    "output": "Stage labor cost, fully loaded labor, price floor.",
    "level": "Target Architecture",
    "usedIn": "Stage labor cost, fully loaded labor, price floor."
  },
  {
    "id": "TBE-HND-017",
    "block": "Item Handling / Crew Feasibility",
    "name": "Hard Access Crew Rule",
    "formula": "IF heavyItem AND hardAccessConstraint THEN minCrew = 2 OR manualReview = TRUE",
    "description": "Если тяжелый предмет сочетается со stairs/no elevator/long carry/narrow access, система должна поднимать min crew или отправлять заказ на manual review.",
    "source": "Heavy item flags, Access Conditions, Location / Address Types, Physical Access Feasibility Rules.",
    "output": "Final stage crew, access risk, labor cost, approval workflow.",
    "level": "Target Architecture",
    "usedIn": "Final stage crew, access risk, labor cost, approval workflow."
  },
  {
    "id": "TBE-VEH-002",
    "block": "Vehicle",
    "name": "Vehicle Dimensional Fit",
    "formula": "vehicleDimensionalFit = itemLength <= cargoInteriorLengthIn AND itemWidth <= cargoInteriorWidthIn AND itemHeight <= cargoInteriorHeightIn",
    "description": "Проверяет, входит ли самый крупный item в реальные внутренние габариты кузова. Это отдельная проверка от общего volume/payload.",
    "source": "Item dimensions; Vehicle Dimensions / Cargo Body Specs reference.",
    "output": "Vehicle selection, manual review, box truck recommendation.",
    "level": "Target Architecture",
    "usedIn": "Vehicle selection, manual review, box truck recommendation."
  },
  {
    "id": "TBE-VEH-003",
    "block": "Vehicle",
    "name": "Door Opening Fit",
    "formula": "doorOpeningFit = itemWidth <= doorOpeningWidthIn AND itemHeight <= doorOpeningHeightIn",
    "description": "Даже если item помещается внутри кузова, он может не пройти через задний/боковой проем. Это должно давать warning/manual review.",
    "source": "Item dimensions; vehicle door opening dimensions.",
    "output": "Physical feasibility, manual review, vehicle upgrade.",
    "level": "Target Architecture",
    "usedIn": "Physical feasibility, manual review, vehicle upgrade."
  },
  {
    "id": "TBE-VEH-004",
    "block": "Vehicle",
    "name": "Selected Vehicle Height Check",
    "formula": "selectedVehicleHeightExceeded = itemHeight > selectedVehicle.cargoInteriorHeightIn",
    "description": "Проверяет не абстрактный threshold, а фактическую высоту кузова выбранной в заявке машины. Если item выше кузова выбранной машины, нужен review и подбор vehicle с более высоким кузовом.",
    "source": "Item height from Quote Draft item row / catalog; selected vehicle cargoInteriorHeightIn from Vehicle Dimensions / Cargo Body Specs.",
    "output": "Vehicle revision, side transport review, box truck recommendation, snapshot warning.",
    "level": "Target Architecture",
    "usedIn": "Vehicle revision, side transport review, box truck recommendation, snapshot warning."
  },
  {
    "id": "TBE-VEH-005",
    "block": "Vehicle",
    "name": "Side Transport Review",
    "formula": "sideTransportReview = selectedVehicleHeightExceeded AND sideTransportAllowed IS NOT TRUE",
    "description": "Если item не входит по высоте в выбранную машину, нельзя автоматически считать, что его повезут на боку. Если side transport не подтвержден, заказ требует review.",
    "source": "Selected vehicle height check, item handling rules, packaging/protection, broker/ops approval.",
    "output": "Manual review, protection/packaging risk, vehicle requirement.",
    "level": "Target Architecture",
    "usedIn": "Manual review, protection/packaging risk, vehicle requirement."
  },
  {
    "id": "TBE-VEH-006",
    "block": "Vehicle",
    "name": "Higher Body Vehicle / Box Truck Recommended",
    "formula": "higherBodyVehicleRecommended = selectedVehicleHeightExceeded AND sideTransportAllowed = FALSE",
    "description": "Если item выше кузова выбранной машины и перевозка на боку не подтверждена, система должна предложить пересмотреть выбранный truck на машину с более высоким кузовом, включая Box Truck если он подходит.",
    "source": "Selected vehicle height check, side transport approval, Vehicle Dimensions reference.",
    "output": "Vehicle selection, quote warning, route cost, final price.",
    "level": "Target Architecture",
    "usedIn": "Vehicle selection, quote warning, route cost, final price."
  },
  {
    "id": "TBE-VEH-007",
    "block": "Vehicle",
    "name": "Vehicle Equipment Requirement",
    "formula": "equipmentRequired = rampRequired OR liftGateRequired OR tieDownRequired; vehicleEligible = vehicle has required equipment",
    "description": "Для некоторых oversized/tall/heavy items нужен ramp, liftgate или tie-down. Vehicle fit должен проверять не только размеры, но и оборудование.",
    "source": "Item handling rules; vehicle equipment fields.",
    "output": "Vehicle eligibility, labor time, manual review.",
    "level": "Target Architecture",
    "usedIn": "Vehicle eligibility, labor time, manual review."
  },
  {
    "id": "TBE-VEH-008",
    "block": "Vehicle",
    "name": "Final Vehicle Eligibility",
    "formula": "vehicleEligible = volumeFit AND payloadFit AND vehicleDimensionalFit AND doorOpeningFit AND equipmentFit",
    "description": "Финальная пригодность машины должна учитывать volume, weight, реальные габариты кузова, дверной проем и оборудование.",
    "source": "Vehicle fit formulas, item dimensions, vehicle dimensions/equipment reference.",
    "output": "Selected vehicle, manual review, cost base.",
    "level": "Target Architecture",
    "usedIn": "Selected vehicle, manual review, cost base."
  },
  {
    "id": "TBE-CAP-005",
    "block": "Capacity / Density",
    "name": "Shipment Density",
    "formula": "shipmentDensityLbPerCuFt = totalWeightLb / MAX(totalEffectiveVolumeCuFt, 1)",
    "description": "Показывает, насколько заказ тяжелый относительно занимаемого объема. Нужен, чтобы отличать легкий объемный заказ от тяжелого компактного заказа.",
    "source": "Total weight из item rows; total effective volume из item calculation.",
    "output": "Capacity constraint, vehicle fit, interstate pricing.",
    "level": "Target Architecture",
    "usedIn": "Capacity constraint, vehicle fit, interstate pricing."
  },
  {
    "id": "TBE-CAP-006",
    "block": "Capacity / Density",
    "name": "Vehicle Density Capacity",
    "formula": "vehicleDensityCapacityLbPerCuFt = selectedVehiclePayloadLb / selectedVehicleCargoVolumeCuFt",
    "description": "Показывает среднюю плотность груза, которую выбранный транспорт может безопасно везти при полной загрузке по объему и весу.",
    "source": "Vehicle body specs reference: payload, cargo volume.",
    "output": "Density comparison, limiting factor selection.",
    "level": "Target Architecture",
    "usedIn": "Density comparison, limiting factor selection."
  },
  {
    "id": "TBE-CAP-007",
    "block": "Capacity / Density",
    "name": "Capacity Constraint Type",
    "formula": "IF payloadUtilization > vehicleUtilization THEN Weight-limited ELSE Volume-limited",
    "description": "Определяет, что именно ограничивает заказ: вес или объем. Для подушек обычно volume-limited, для мрамора weight-limited.",
    "source": "Payload utilization and volume utilization.",
    "output": "Pricing explanation, warning rules, route capacity pricing.",
    "level": "Target Architecture",
    "usedIn": "Pricing explanation, warning rules, route capacity pricing."
  },
  {
    "id": "TBE-CAP-008",
    "block": "Capacity / Density",
    "name": "Limiting Capacity Factor",
    "formula": "limitingCapacityFactor = MAX(vehicleUtilization, payloadUtilization)",
    "description": "Для pricing берется больший процент загрузки: если объем занят на 30%, а вес на 70%, стоимость capacity должна считаться от 70%.",
    "source": "Vehicle utilization and payload utilization.",
    "output": "Interstate capacity cost, bulky premium, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Interstate capacity cost, bulky premium, margin guardrail."
  },
  {
    "id": "TBE-CAP-009",
    "block": "Capacity / Density",
    "name": "Interstate Capacity Cost",
    "formula": "interstateCapacityCost = fullRouteCapacityCost * limitingCapacityFactor",
    "description": "Считает долю стоимости interstate truck/route, которую занимает заказ, с учетом и объема, и веса.",
    "source": "Route cost reference, selected interstate vehicle, limiting capacity factor.",
    "output": "Interstate subtotal, final cost base.",
    "level": "Target Architecture",
    "usedIn": "Interstate subtotal, final cost base."
  },
  {
    "id": "TBE-CAP-010",
    "block": "Capacity / Density",
    "name": "Legacy Dual Cost Guardrail",
    "formula": "interstateCapacityCost = MAX(totalEffectiveVolume * costPerCuFt, totalWeight * costPerLb)",
    "description": "Альтернативный guardrail из старой логики: считаем цену по объему и по весу, затем берем большее значение, чтобы не недооценить тяжелые компактные заказы.",
    "source": "Cost per cubic foot and cost per pound variables/reference.",
    "output": "Interstate subtotal or margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Interstate subtotal or margin guardrail."
  },
  {
    "id": "TBE-CAP-011",
    "block": "Capacity / Density",
    "name": "Capacity Overflow Flag",
    "formula": "capacityOverflowFlag = vehicleUtilization > 1 OR payloadUtilization > 1",
    "description": "Ставит красный флаг, если заказ не помещается в выбранный транспорт по объему или payload.",
    "source": "Vehicle utilization, payload utilization.",
    "output": "Warnings, vehicle recommendation, quote approval.",
    "level": "Target Architecture",
    "usedIn": "Warnings, vehicle recommendation, quote approval."
  },
  {
    "id": "TBE-TIME-011",
    "block": "Time / Labor",
    "name": "Historical Time Calibration",
    "formula": "timeCoefficient = calibrated from measured historical stop/stage time",
    "description": "Коэффициенты времени должны опираться на реальные замеры заказов, а не на догадку. В транскрибе обсуждалась база около 100 заказов.",
    "source": "Historical Time Metrics reference.",
    "output": "Pickup/delivery/loading/unloading time model.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery/loading/unloading time model."
  },
  {
    "id": "TBE-TIME-012",
    "block": "Time / Labor",
    "name": "Pickup Loading Minutes",
    "formula": "pickupLoadingMinutes = loadingFormula(totalEffectiveVolume) + weightHandlingMinutes + accessTimeImpact",
    "description": "Считает время погрузки на pickup с учетом объема, веса и условий доступа.",
    "source": "Item volume/weight, loading variables, access conditions.",
    "output": "Pickup labor cost, crew paid minutes.",
    "level": "Target Architecture",
    "usedIn": "Pickup labor cost, crew paid minutes."
  },
  {
    "id": "TBE-TIME-013",
    "block": "Time / Labor",
    "name": "Delivery Unloading Minutes",
    "formula": "deliveryUnloadingMinutes = pickupLoadingMinutes * unloadingTimeCoefficient",
    "description": "Delivery обычно быстрее pickup, поэтому unloading coefficient должен быть отдельной переменной, а не скрытой константой.",
    "source": "Pickup loading minutes; unloading coefficient variable.",
    "output": "Delivery labor cost, delivery subtotal.",
    "level": "Target Architecture",
    "usedIn": "Delivery labor cost, delivery subtotal."
  },
  {
    "id": "TBE-TIME-014",
    "block": "Time / Labor",
    "name": "Helper Paid Minutes",
    "formula": "helperPaidMinutes = MAX(helperActiveMinutes, helperMinimumBillableMinutes)",
    "description": "Если нужен helper, оплачиваемое время не должно быть меньше минимального порога, даже если активная работа заняла меньше.",
    "source": "Helper active minutes, helper minimum billable minutes.",
    "output": "Payroll, margin, final price.",
    "level": "Target Architecture",
    "usedIn": "Payroll, margin, final price."
  },
  {
    "id": "TBE-TIME-015",
    "block": "Time / Labor",
    "name": "Fully Loaded Labor Cost",
    "formula": "fullyLoadedLaborCost = SUM(rolePaidHours * fullyLoadedHourlyRateByRole)",
    "description": "Считает реальную себестоимость труда, включая ставку, налоги/overhead/прочие нагрузки, а не только выплату человеку.",
    "source": "Payroll roles/wage rates reference.",
    "output": "Direct cost base, margin calculation.",
    "level": "Target Architecture",
    "usedIn": "Direct cost base, margin calculation."
  },
  {
    "id": "TBE-ACC-006",
    "block": "Access Conditions",
    "name": "Billable Floors",
    "formula": "billableFloors = MAX(addressFloor - freeFloorCount, 0)",
    "description": "Считает только платные этажи. Если первые этажи бесплатны, fee начинается после утвержденного free floor threshold.",
    "source": "Address access conditions; free floor count variable.",
    "output": "Stairs fee, access time impact.",
    "level": "Target Architecture",
    "usedIn": "Stairs fee, access time impact."
  },
  {
    "id": "TBE-ACC-007",
    "block": "Access Conditions",
    "name": "Stairs Fee",
    "formula": "stairsFee = billableFloors * stairsFeePerBillableFloor * stairsItemOrOrderMultiplier",
    "description": "Считает fee за лестницу только по billable floors. Множитель нужен, если fee зависит от заказа, item count или heavy items.",
    "source": "Billable floors, stairs fee variable, item/order multiplier.",
    "output": "Pickup/delivery access subtotal.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery access subtotal."
  },
  {
    "id": "TBE-ACC-008",
    "block": "Access Conditions",
    "name": "Extra Labor Cost",
    "formula": "extraLaborCost = extraLaborPeople * MAX(extraLaborHours, extraLaborMinimumHours) * extraLaborHourlyRate",
    "description": "Если вручную добавлен extra labor, расчет должен учитывать minimum hours и ставку, чтобы не терять маржу на коротких работах.",
    "source": "Quote options; labor variables.",
    "output": "Access/service subtotal, payroll, margin.",
    "level": "Target Architecture",
    "usedIn": "Access/service subtotal, payroll, margin."
  },
  {
    "id": "TBE-WARN-001",
    "block": "Warnings / Approval",
    "name": "Warning Rule Evaluation",
    "formula": "warningActive = ruleCondition = TRUE",
    "description": "Каждое риск-условие должно превращаться в понятный warning: что случилось, почему важно, блокирует ли quote и кто должен approve.",
    "source": "Warning rules reference; formula outputs.",
    "output": "Broker UI, admin breakdown, approval workflow.",
    "level": "Target Architecture",
    "usedIn": "Broker UI, admin breakdown, approval workflow."
  },
  {
    "id": "TBE-WARN-002",
    "block": "Warnings / Approval",
    "name": "Vehicle Fit Warning",
    "formula": "vehicleFitWarning = selectedVehicleHeightExceeded OR widthExceeded OR lengthExceeded OR payloadUtilization > 1 OR vehicleUtilization > 1",
    "description": "Показывает, что выбранная машина физически или по payload не подходит заказу.",
    "source": "Vehicle body specs; item dimensions; utilization outputs.",
    "output": "Quote warnings, vehicle recommendation, manager approval.",
    "level": "Target Architecture",
    "usedIn": "Quote warnings, vehicle recommendation, manager approval."
  },
  {
    "id": "TBE-WARN-003",
    "block": "Warnings / Approval",
    "name": "Crew Review Warning",
    "formula": "crewReviewWarning = maxSingleItemWeight > heavyItemThreshold OR requiredCrewSize > standardCrewSize",
    "description": "Ставит red flag, когда заказ нельзя надежно делать стандартной командой.",
    "source": "Item handling rules; max unit weight; required crew.",
    "output": "Broker warning, manager approval, labor cost.",
    "level": "Target Architecture",
    "usedIn": "Broker warning, manager approval, labor cost."
  },
  {
    "id": "TBE-WARN-004",
    "block": "Warnings / Approval",
    "name": "Quote Can Save",
    "formula": "quoteCanSave = noBlockingWarnings OR allRequiredApprovalsCompleted",
    "description": "Определяет, можно ли сохранить/отправить estimate, если есть red flags.",
    "source": "Warning rules, approval status.",
    "output": "Estimate workflow, snapshot.",
    "level": "Target Architecture",
    "usedIn": "Estimate workflow, snapshot."
  },
  {
    "id": "TBE-MRG-011",
    "block": "Margin / Compensation",
    "name": "Contribution Margin",
    "formula": "contributionMargin = finalCustomerPrice - directCost - payrollCost - brokerPayout - dispatcherPayout - allocatedOverhead",
    "description": "Показывает реальную прибыльность заказа после прямых расходов, выплат и распределенного overhead.",
    "source": "Final price, direct costs, payroll, compensation references.",
    "output": "Margin guardrail, CEO reporting.",
    "level": "Target Architecture",
    "usedIn": "Margin guardrail, CEO reporting."
  },
  {
    "id": "TBE-MRG-012",
    "block": "Margin / Compensation",
    "name": "Discount Order Guardrail",
    "formula": "discountedPrice = applyDiscountAfterOrBeforeMargin(priceBase, discountRule)",
    "description": "Фиксирует, на каком этапе применяется discount, чтобы скидка не уничтожала margin незаметно.",
    "source": "Discount rule, margin rule, price build order.",
    "output": "Final customer price, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Final customer price, margin guardrail."
  },
  {
    "id": "TBE-MRG-013",
    "block": "Margin / Compensation",
    "name": "Broker Payout",
    "formula": "brokerPayout = payoutBase * brokerCommissionRate OR fixedBrokerFee",
    "description": "Считает выплату брокеру по утвержденному плану: процент, fixed fee или гибрид.",
    "source": "Broker compensation plan reference; order source/channel.",
    "output": "Contribution margin, payroll/payout reporting.",
    "level": "Target Architecture",
    "usedIn": "Contribution margin, payroll/payout reporting."
  },
  {
    "id": "TBE-MRG-014",
    "block": "Margin / Compensation",
    "name": "Dispatcher Payout",
    "formula": "dispatcherPayout = dispatcherPlan(order, route, stage, revenue, KPI)",
    "description": "Считает выплату диспетчеру по утвержденной модели: fixed/order, per route, KPI или процент.",
    "source": "Dispatcher compensation plan reference.",
    "output": "Contribution margin, payout reporting.",
    "level": "Target Architecture",
    "usedIn": "Contribution margin, payout reporting."
  },
  {
    "id": "TBE-RTE-011",
    "block": "Route / ZIP Governance",
    "name": "Manual ZIP Override",
    "formula": "effectiveZone = manualOverrideZone IF approved ELSE zipDictionaryZone",
    "description": "Позволяет вручную добавить/исключить ZIP или изменить зону без переписывания логики калькулятора.",
    "source": "ZIP dictionary; manual override approval.",
    "output": "Route classification, fees, warnings.",
    "level": "Target Architecture",
    "usedIn": "Route classification, fees, warnings."
  },
  {
    "id": "TBE-RTE-012",
    "block": "Route / ZIP Governance",
    "name": "Corridor / Remote Multiplier",
    "formula": "routeZonePremium = baseRouteCost * zoneMultiplier OR fixedZoneFee",
    "description": "Отдельно учитывает corridor/remote pricing, чтобы удаленные или неудобные направления не продавались по средней цене.",
    "source": "Service area and ZIP dictionary zone class.",
    "output": "Route subtotal, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Route subtotal, margin guardrail."
  },
  {
    "id": "TBE-SNAP-002",
    "block": "Snapshot Compatibility",
    "name": "Variable Snapshot",
    "formula": "variablesSnapshot = all variable IDs + values + version + effective date used in quote",
    "description": "Сохраняет именно те значения переменных, по которым был рассчитан estimate, чтобы старый estimate не менялся после изменения настроек.",
    "source": "Pricing variable store at calculation time.",
    "output": "Estimate snapshot, audit, admin breakdown.",
    "level": "Target Architecture",
    "usedIn": "Estimate snapshot, audit, admin breakdown."
  },
  {
    "id": "TBE-SNAP-003",
    "block": "Snapshot Compatibility",
    "name": "Reference Snapshot",
    "formula": "referencesSnapshot = reference versions used in quote",
    "description": "Фиксирует версии справочников: vehicles, ZIP, rates, plans, labor, чтобы расчет был воспроизводим.",
    "source": "Reference version registry.",
    "output": "Estimate snapshot, audit.",
    "level": "Target Architecture",
    "usedIn": "Estimate snapshot, audit."
  },
  {
    "id": "INT-CAP-001-DENSITY-THRESHOLD",
    "block": "Interstate Capacity Logic",
    "name": "Density Threshold",
    "formula": "densityThresholdLbPerCuFt = vehiclePayloadLb / vehicleCapacityCuFt",
    "description": "Порог плотности выбранного interstate vehicle. Если shipment density выше этого значения, заказ быстрее упирается в вес, чем в объем. Значение 5.33 для 8000 lb / 1500 cu ft является примером расчета, а не hardcoded constant.",
    "source": "Vehicle Reference / Vehicle Body Specs: payloadLb, capacityCuFt.",
    "output": "Shipment density comparison, interstate cost basis, warning engine.",
    "level": "Target Architecture",
    "usedIn": "Shipment density comparison, interstate cost basis, warning engine."
  },
  {
    "id": "INT-CAP-002-VOLUME-UTILIZATION",
    "block": "Interstate Capacity Logic",
    "name": "Volume Utilization",
    "formula": "volumeUtilization = effectiveVolumeCuFt / vehicleCapacityCuFt",
    "description": "Показывает, какую долю объема interstate truck занимает заказ.",
    "source": "Effective volume from item calculations; vehicle capacity from vehicle reference.",
    "output": "Capacity constraint selector, interstate cost basis, volume fit warning.",
    "level": "Target Architecture",
    "usedIn": "Capacity constraint selector, interstate cost basis, volume fit warning."
  },
  {
    "id": "INT-CAP-003-PAYLOAD-UTILIZATION",
    "block": "Interstate Capacity Logic",
    "name": "Payload Utilization",
    "formula": "payloadUtilization = totalWeightLb / vehiclePayloadLb",
    "description": "Показывает, какую долю payload выбранного interstate truck занимает заказ.",
    "source": "Total weight from item rows; vehicle payload from vehicle reference.",
    "output": "Capacity constraint selector, interstate cost basis, payload fit warning.",
    "level": "Target Architecture",
    "usedIn": "Capacity constraint selector, interstate cost basis, payload fit warning."
  },
  {
    "id": "INT-CAP-004-CAPACITY-CONSTRAINT-SELECTOR",
    "block": "Interstate Capacity Logic",
    "name": "Capacity Constraint Selector",
    "formula": "capacityConstraint = IF(payloadUtilization > volumeUtilization, Weight-limited, Volume-limited)",
    "description": "Выбирает, чем ограничен заказ: весом или объемом. Это объясняет разницу между pillows и marble countertop.",
    "source": "Volume utilization and payload utilization.",
    "output": "Pricing trace, warning engine, interstate pricing basis.",
    "level": "Target Architecture",
    "usedIn": "Pricing trace, warning engine, interstate pricing basis."
  },
  {
    "id": "INT-CAP-005-INTERSTATE-COST-BASIS",
    "block": "Interstate Capacity Logic",
    "name": "Interstate Cost Basis",
    "formula": "interstateCostBasis = MAX(volumeUtilization, payloadUtilization)",
    "description": "Для interstate pricing берется больший utilization. Если объем 30%, а payload 70%, cost basis = 70%.",
    "source": "Volume utilization and payload utilization.",
    "output": "Interstate capacity cost, route subtotal, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Interstate capacity cost, route subtotal, margin guardrail."
  },
  {
    "id": "INT-CAP-006-VOLUME-LIMITED-LOAD",
    "block": "Interstate Capacity Logic",
    "name": "Volume Limited Load",
    "formula": "volumeLimitedLoad = volumeUtilization >= payloadUtilization",
    "description": "Флаг, что заказ ограничен объемом. Пример: 1000 pillows занимают кузов, но почти не используют payload.",
    "source": "Volume utilization and payload utilization.",
    "output": "Interstate trace, warning engine, route capacity economics.",
    "level": "Target Architecture",
    "usedIn": "Interstate trace, warning engine, route capacity economics."
  },
  {
    "id": "INT-CAP-007-WEIGHT-LIMITED-LOAD",
    "block": "Interstate Capacity Logic",
    "name": "Weight Limited Load",
    "formula": "weightLimitedLoad = payloadUtilization > volumeUtilization",
    "description": "Флаг, что заказ ограничен весом. Пример: marble countertops могут перегрузить payload при пустом кузове.",
    "source": "Volume utilization and payload utilization.",
    "output": "Interstate trace, warning engine, route capacity economics.",
    "level": "Target Architecture",
    "usedIn": "Interstate trace, warning engine, route capacity economics."
  },
  {
    "id": "LAB-TIME-001-VOLUME-BASED-HANDLING-TIME",
    "block": "Labor Time Architecture",
    "name": "Volume Based Handling Time",
    "formula": "volumeHandlingMinutes = effectiveVolumeCuFt * minutesPerCuFt",
    "description": "Считает labor time по объему. Используется как один из двух сценариев, но не суммируется с weight time.",
    "source": "Effective volume from item calculations; minutesPerCuFt variable.",
    "output": "Handling time selector.",
    "level": "Target Architecture",
    "usedIn": "Handling time selector."
  },
  {
    "id": "LAB-TIME-002-WEIGHT-BASED-HANDLING-TIME",
    "block": "Labor Time Architecture",
    "name": "Weight Based Handling Time",
    "formula": "weightHandlingMinutes = totalWeightLb * minutesPerLb",
    "description": "Считает labor time по весу. Используется как второй сценарий, чтобы тяжелые компактные заказы не были недооценены.",
    "source": "Total weight from item rows; minutesPerLb variable.",
    "output": "Handling time selector.",
    "level": "Target Architecture",
    "usedIn": "Handling time selector."
  },
  {
    "id": "LAB-TIME-003-HANDLING-TIME-SELECTOR",
    "block": "Labor Time Architecture",
    "name": "Handling Time Selector",
    "formula": "baseHandlingMinutes = MAX(volumeHandlingMinutes, weightHandlingMinutes)",
    "description": "Ключевое правило из meeting: не суммировать volume time и weight time, а брать большее значение, чтобы избежать double-counting.",
    "source": "Volume handling minutes and weight handling minutes.",
    "output": "Pickup/delivery split, labor cost, trace.",
    "level": "Target Architecture",
    "usedIn": "Pickup/delivery split, labor cost, trace."
  },
  {
    "id": "LAB-TIME-004-PICKUP-DELIVERY-TIME-SPLIT",
    "block": "Labor Time Architecture",
    "name": "Pickup / Delivery Time Split",
    "formula": "pickupHandlingMinutes = baseHandlingMinutes * pickupTimeMultiplier; deliveryHandlingMinutes = baseHandlingMinutes * deliveryTimeMultiplier",
    "description": "Pickup и delivery должны иметь разные коэффициенты. Delivery обычно быстрее pickup, но оба коэффициента должны быть variables.",
    "source": "Base handling minutes; pickup/delivery time multiplier variables.",
    "output": "Pickup subtotal, delivery subtotal, payroll, margin.",
    "level": "Target Architecture",
    "usedIn": "Pickup subtotal, delivery subtotal, payroll, margin."
  },
  {
    "id": "LAB-TIME-005-MINIMUM-HANDLING-TIME",
    "block": "Labor Time Architecture",
    "name": "Minimum Handling Time",
    "formula": "handlingMinutes = MAX(calculatedHandlingMinutes, minimumHandlingMinutes)",
    "description": "Не позволяет коротким заказам падать ниже минимального операционного времени.",
    "source": "Calculated handling minutes; minimumHandlingMinutes variable.",
    "output": "Labor cost, stage subtotal, margin guardrail.",
    "level": "Target Architecture",
    "usedIn": "Labor cost, stage subtotal, margin guardrail."
  },
  {
    "id": "LAB-TIME-006-PICKUP-TIME-COEFFICIENT",
    "block": "Labor Time Architecture",
    "name": "Pickup Time Coefficient",
    "formula": "pickupHandlingMinutes = baseHandlingMinutes * pickupTimeMultiplier",
    "description": "Отдельный коэффициент pickup отражает check-in, упаковку, подготовку и более долгую операцию на pickup.",
    "source": "Base handling minutes; pickupTimeMultiplier variable; historical time metrics.",
    "output": "Pickup labor cost and pickup subtotal.",
    "level": "Target Architecture",
    "usedIn": "Pickup labor cost and pickup subtotal."
  },
  {
    "id": "LAB-TIME-007-DELIVERY-TIME-COEFFICIENT",
    "block": "Labor Time Architecture",
    "name": "Delivery Time Coefficient",
    "formula": "deliveryHandlingMinutes = baseHandlingMinutes * deliveryTimeMultiplier",
    "description": "Отдельный коэффициент delivery отражает, что unloading обычно быстрее loading/pickup.",
    "source": "Base handling minutes; deliveryTimeMultiplier variable; historical time metrics.",
    "output": "Delivery labor cost and delivery subtotal.",
    "level": "Target Architecture",
    "usedIn": "Delivery labor cost and delivery subtotal."
  },
  {
    "id": "FIT-001-DIMENSIONAL-FIT",
    "block": "Vehicle Fit / Capacity Fit",
    "name": "Dimensional Fit",
    "formula": "dimensionalFit = maxItemLength <= vehicleInteriorLength AND maxItemWidth <= vehicleInteriorWidth AND maxItemHeight <= vehicleInteriorHeight",
    "description": "Проверяет, входит ли самый крупный item в реальные внутренние габариты выбранного vehicle.",
    "source": "Item max dimensions; Vehicle Body Specs reference.",
    "output": "Vehicle fit, warning engine, recommended vehicle change.",
    "level": "Target Architecture",
    "usedIn": "Vehicle fit, warning engine, recommended vehicle change."
  },
  {
    "id": "FIT-002-CAPACITY-FIT-BY-VOLUME",
    "block": "Vehicle Fit / Capacity Fit",
    "name": "Capacity Fit By Volume",
    "formula": "volumeFit = effectiveVolumeCuFt <= vehicleCapacityCuFt",
    "description": "Проверяет, помещается ли заказ в выбранный vehicle по total effective volume.",
    "source": "Effective volume; vehicle capacity.",
    "output": "Vehicle fit, warning engine, vehicle recommendation.",
    "level": "Target Architecture",
    "usedIn": "Vehicle fit, warning engine, vehicle recommendation."
  },
  {
    "id": "FIT-003-CAPACITY-FIT-BY-WEIGHT",
    "block": "Vehicle Fit / Capacity Fit",
    "name": "Capacity Fit By Weight",
    "formula": "weightFit = totalWeightLb <= vehiclePayloadLb",
    "description": "Проверяет, помещается ли заказ в выбранный vehicle по payload.",
    "source": "Total weight; vehicle payload.",
    "output": "Vehicle fit, warning engine, vehicle recommendation.",
    "level": "Target Architecture",
    "usedIn": "Vehicle fit, warning engine, vehicle recommendation."
  },
  {
    "id": "FIT-004-FIT-FAILURE-WARNING",
    "block": "Vehicle Fit / Capacity Fit",
    "name": "Fit Failure Warning",
    "formula": "vehicleFit = dimensionalFit AND volumeFit AND weightFit; IF vehicleFit = FALSE THEN warning",
    "description": "Если хотя бы одна fit-проверка не проходит, заказ должен получить warning и review/recommendation.",
    "source": "Dimensional fit, volume fit, weight fit.",
    "output": "Warning engine, quote save logic, manager approval.",
    "level": "Target Architecture",
    "usedIn": "Warning engine, quote save logic, manager approval."
  },
  {
    "id": "FIT-005-RECOMMENDED-VEHICLE-CHANGE",
    "block": "Vehicle Fit / Capacity Fit",
    "name": "Recommended Vehicle Change",
    "formula": "recommendedVehicle = smallest approved vehicle where dimensionalFit AND volumeFit AND weightFit",
    "description": "Если выбранный vehicle не подходит, система должна предложить минимальный следующий vehicle, который закрывает габариты, объем и payload.",
    "source": "Vehicle Body Specs reference; fit outputs.",
    "output": "Broker/admin recommendation, warnings, pricing recalculation.",
    "level": "Target Architecture",
    "usedIn": "Broker/admin recommendation, warnings, pricing recalculation."
  },
  {
    "id": "WARN-001-HEAVY-ITEM",
    "block": "WARNING_ENGINE",
    "name": "Heavy Item Warning",
    "formula": "warningActive = maxItemWeightLb > heavyItemThresholdLb",
    "description": "Red flag для тяжелого единичного предмета. Влияет на helper, crew, time и manager review.",
    "source": "Max single item weight; heavy item threshold variable.",
    "output": "Warning list, crew logic, approval workflow.",
    "level": "Target Architecture",
    "usedIn": "Warning list, crew logic, approval workflow."
  },
  {
    "id": "WARN-002-BULKY-ORDER",
    "block": "WARNING_ENGINE",
    "name": "Bulky Order Warning",
    "formula": "warningActive = totalEffectiveVolumeCuFt > bulkyVolumeThresholdCuFt",
    "description": "Red flag для bulky/moving-like заказа, который занимает значительную capacity.",
    "source": "Total effective volume; bulky volume threshold variable.",
    "output": "Warning list, capacity premium, route capacity pricing.",
    "level": "Target Architecture",
    "usedIn": "Warning list, capacity premium, route capacity pricing."
  },
  {
    "id": "WARN-003-ITEM-DOES-NOT-FIT-VEHICLE",
    "block": "WARNING_ENGINE",
    "name": "Item Does Not Fit Vehicle",
    "formula": "warningActive = dimensionalFit = FALSE OR volumeFit = FALSE OR weightFit = FALSE",
    "description": "Предупреждение, что выбранный vehicle не подходит по габаритам, объему или весу.",
    "source": "FIT-001/FIT-002/FIT-003 outputs.",
    "output": "Quote blocking, vehicle recommendation, manager approval.",
    "level": "Target Architecture",
    "usedIn": "Quote blocking, vehicle recommendation, manager approval."
  },
  {
    "id": "WARN-004-MORE-THAN-2-PEOPLE",
    "block": "WARNING_ENGINE",
    "name": "More Than 2 People Required",
    "formula": "warningActive = requiredCrewSize > 2",
    "description": "Предупреждение, что заказ требует больше стандартной команды.",
    "source": "Crew calculation, item handling rules, access conditions.",
    "output": "Labor cost, approval workflow, broker warning.",
    "level": "Target Architecture",
    "usedIn": "Labor cost, approval workflow, broker warning."
  },
  {
    "id": "WARN-005-OUT-OF-ZONE",
    "block": "WARNING_ENGINE",
    "name": "Out Of Zone Warning",
    "formula": "warningActive = zoneClass = outOfZone OR ZIP not supported",
    "description": "Предупреждение для ZIP/route вне стандартной зоны.",
    "source": "ZIP dictionary, service areas, manual override register.",
    "output": "Route pricing, approval workflow, quote save logic.",
    "level": "Target Architecture",
    "usedIn": "Route pricing, approval workflow, quote save logic."
  },
  {
    "id": "WARN-006-DIRECT-SERVICE-REVIEW",
    "block": "WARNING_ENGINE",
    "name": "Direct Service Review",
    "formula": "warningActive = directFlag = TRUE OR specificDateFlag = TRUE",
    "description": "Direct/specific-date service ломает consolidated route economics и требует отдельной fee/distance логики.",
    "source": "Quote service flags, route type.",
    "output": "Direct fee, route recalculation, approval workflow.",
    "level": "Target Architecture",
    "usedIn": "Direct fee, route recalculation, approval workflow."
  },
  {
    "id": "WARN-007-MANAGER-APPROVAL-REQUIRED",
    "block": "WARNING_ENGINE",
    "name": "Manager Approval Required",
    "formula": "managerApprovalRequired = anyBlockingWarning OR approvalRuleTriggered",
    "description": "Общий флаг, что quote нельзя считать финальным без manager approval.",
    "source": "Warning engine outputs, approval rules reference.",
    "output": "Quote can save, snapshot, audit trail.",
    "level": "Target Architecture",
    "usedIn": "Quote can save, snapshot, audit trail."
  }
];
window.FormulaCatalogMetadata = {
  "variableTerms": [
    "roundingIncrement",
    "marginRate",
    "brokerFeeRate",
    "directFixedFee",
    "directMileageFee",
    "remoteZoneCoefficient",
    "bulkyVolumeThreshold",
    "pickupTimeCoefficients",
    "deliveryTimeCoefficients",
    "crateMaterialPrice",
    "crateWasteCoefficient",
    "storageRate",
    "fvpRate / fvpFixedFee",
    "managementFee",
    "hourlyWageByRole",
    "overtimeMultiplier",
    "payrollBurdenRate",
    "brokerCommissionRate",
    "dispatcherPayoutRate",
    "minContributionMarginPct",
    "overheadAllocationRate",
    "routeCapacityRate",
    "bulkyPremiumMultiplier",
    "locationTypeTimeMultiplier",
    "locationTypeFixedMinutes",
    "locationTypeCrewImpact",
    "parkingLoadingComplexityMinutes",
    "warehouseEfficiencyFactor",
    "auctionHandlingMinutes",
    "timeDataConfidenceScore",
    "minimumTimeSampleSize",
    "timeEstimateBufferPct",
    "onePersonMaxItemWeightLb",
    "twoPersonItemWeightThresholdLb",
    "awkwardItemLengthThresholdIn",
    "itemMinimumHandlingMinutes",
    "largeLightItemVolumeThresholdCuFt",
    "itemHandlingScoreThreshold",
    "heavyPieceWeightThresholdLb",
    "onePersonPieceLimit",
    "minutesPerPieceByHandlingClass",
    "helperActiveMinutesPerHeavyPiece",
    "partialHelperBillingPolicy",
    "hardAccessConstraintRule",
    "accessHeavyImpactMinutes",
    "physicalFeasibilityReviewThreshold",
    "selectedVehicleCargoHeightIn",
    "sideTransportAllowed",
    "sideTransportApprovalRequired",
    "cargoInteriorLengthIn",
    "cargoInteriorWidthIn",
    "cargoInteriorHeightIn",
    "doorOpeningWidthIn",
    "doorOpeningHeightIn",
    "vehicleEquipmentFlags",
    "selectedVehicleCargoVolumeCuFt",
    "selectedVehiclePayloadLb",
    "fullRouteCapacityCost",
    "interstateCostPerCuFt",
    "interstateCostPerLb",
    "capacityPricingMethod",
    "loadingCurveVolumeThresholdCuFt",
    "loadingCurveNumerator",
    "loadingCurveDenominatorOffset",
    "loadingCurveBaseMinutes",
    "loadingPostThresholdMinutesPerCuFt",
    "unloadingTimeCoefficient",
    "freeFloorCount",
    "stairsFeePerBillableFloor",
    "extraLaborMinimumHours",
    "extraLaborHourlyRate",
    "blockingWarningFlag",
    "minimumContributionMarginRate",
    "discountApplicationOrder",
    "brokerCommissionRate",
    "dispatcherPayoutRule",
    "zoneMultiplier",
    "minutesPerCuFt",
    "minutesPerLb",
    "pickupTimeMultiplier",
    "deliveryTimeMultiplier",
    "minimumHandlingMinutes",
    "maxItemLength",
    "maxItemWidth",
    "maxItemHeight",
    "vehicleInteriorLength",
    "vehicleInteriorWidth",
    "vehicleInteriorHeight",
    "warningSeverity",
    "managerApprovalRequired"
  ],
  "referenceTerms": [
    "ZIP Dictionary",
    "Service Areas",
    "Distance Matrix / Route Engine",
    "Vehicles",
    "Labor",
    "Items Catalog",
    "Packaging / Crate Materials",
    "Protection Plans",
    "Storage Rates",
    "Benchmark Cases",
    "Payroll Roles / Wage Rates",
    "Broker Compensation Plans",
    "Dispatcher Compensation Plans",
    "Overhead Allocation Rules",
    "Capacity Economics",
    "Location / Address Types",
    "Historical Time Metrics",
    "Access Time Reference",
    "Packaging Time Reference",
    "Crate Labor Reference",
    "Time Data Quality Rules",
    "Item Handling / Crew Feasibility Rules",
    "Physical Access Feasibility Rules",
    "Vehicle Dimensions / Cargo Body Specs",
    "Warning / Approval Rules",
    "Formula Constants Audit",
    "Route Capacity Cost Reference",
    "Formula Version Registry",
    "Manual ZIP Override Register"
  ]
};
