(function () {
  window.CalculatorBlankQuote = {
    estimateId: "EST-NEW",
    status: "draft",
    customer: {
      leadName: "",
      name: "",
      phone: "",
      email: "",
    },
    route: {
      pickupZip: "",
      deliveryZip: "",
      pickupAddress: "",
      deliveryAddress: "",
    },
    access: {
      pickup: { addressType: "House", coi: false, stairs: false, elevatorUnavailable: false, narrowAccess: false, floor: 1, longCarryFt: 0, crew: 0 },
      delivery: { addressType: "House", coi: false, stairs: false, elevatorUnavailable: false, narrowAccess: false, floor: 1, longCarryFt: 0, crew: 0 },
    },
    options: {
      exclusiveDelivery: false,
      priorityDate: false,
      helperRequirement: "Auto",
      deliveryType: "Consolidated Route",
      requestedDate: "",
      manualAdjustment: 0,
      notes: "",
    },
    items: [
      {
        id: "item-blank",
        name: "",
        length: 0,
        width: 0,
        height: 0,
        weight: 0,
        qty: 1,
        packaging: "None",
        insurance: "Basic Liability",
        declaredValue: 0,
        storageDays: 0,
        fragile: false,
        nonStackable: false,
        crated: false,
        comment: "",
      },
    ],
  };

  window.CalculatorMockData = {
    estimateId: "EST-291",
    status: "draft",
    customer: {
      leadName: "Concrete Table - LA",
      name: "Test Customer",
      phone: "+1 555 0100",
      email: "test@example.invalid",
    },
    route: {
      pickupZip: "11211",
      deliveryZip: "90021",
      pickupAddress: "100 Example St, Brooklyn, NY 11211",
      deliveryAddress: "200 Demo Ave, Los Angeles, CA 90021",
    },
    access: {
      pickup: { addressType: "House", coi: false, stairs: false, elevatorUnavailable: false, narrowAccess: false, floor: 1, longCarryFt: 0, crew: 0 },
      delivery: { addressType: "Old Apartment", coi: true, stairs: true, elevatorUnavailable: false, narrowAccess: true, floor: 4, longCarryFt: 50, crew: 0 },
    },
    options: {
      exclusiveDelivery: false,
      priorityDate: false,
      helperRequirement: "Auto",
      deliveryType: "Consolidated Route",
      requestedDate: "",
      manualAdjustment: 0,
      notes: "",
    },
    items: [
      {
        id: "item-1",
        name: "Concrete Table",
        length: 140,
        width: 50,
        height: 20,
        weight: 500,
        qty: 1,
        packaging: "Custom Crate",
        insurance: "Full Coverage",
        declaredValue: 1500,
        storageDays: 3,
        fragile: true,
        nonStackable: true,
        crated: true,
        comment: "Requires careful handling",
      },
      {
        id: "item-2",
        name: "Vintage Mirror",
        length: 40,
        width: 6,
        height: 60,
        weight: 45,
        qty: 1,
        packaging: "Bubble Protection",
        insurance: "Basic Liability",
        declaredValue: 700,
        storageDays: 0,
        fragile: true,
        nonStackable: false,
        crated: false,
        comment: "Fragile antique item",
      },
    ],
  };
})();
